### ISSUE TITLE
aurelia-pal.d.ts is missing

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/pal#12]
`aurelia-pal.d.ts` is missing from module specific folders

**Comment by EisenbergEffect** [comment]
We switched to using the typings filed in the package.json, since that's the way that TS recommends handling this. We're troubleshooting now. Are you having compilation issues?

**Comment by MaximBalaganskiy** [comment]
I did `jspm update` which brought the fresh `aurelia-pal` and removed the `d.ts` file from `jspm_packages` folder

**Comment by MaximBalaganskiy** [comment]
I tried then copying the `d.ts` file from github and it doesn't work because it doesn't declare any modules

**Comment by EisenbergEffect** [comment]
Yes, it's now using the correct format for the typings configuration of the package.json which can be picked up automatically by TypeScript. For the moment, just `npm install aurelia-pal`. That should fix the issue. We'll continue to investigate a better way to handle this for jspm users. We're discussing it now...

**Comment by MaximBalaganskiy** [comment]
Unfortunately, it does not fix it. VS still cannot find module `aurelia-pal`. Moreover, it adds more issues because I have to now include `node_modules` in `tsconfig.json` which has lots of other unneeded `d.ts` files

**Comment by EisenbergEffect** [comment]
You definitely should not include the node modules in your tsconfig.json. That's not how it's supposed to work. TS tooling should pick up the d.ts file automatically because it's defined in the package.json. You may need to comfigure your copmiler differently.

@niieani Can you advise? This is a jspm user that lost d.ts files for pal with today's update. We need to have a nice solution for them.

**Comment by MaximBalaganskiy** [comment]
I'm using TS 1.8. This is my current `tsconfig.json`

```
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "allowUnreachableCode": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
    "exclude": [ "node_modules" ]
}
```

Is there anything else I need to add?

**Comment by dkent600** [comment]
"jspm install" doesn't fix the issue for me either.  still no d.ts.

**Comment by MaximBalaganskiy** [comment]
@dkent600 the workaround is `npm install aurelia-pal` but it does not work either. Might be a tooling problem in VS

**Comment by dkent600** [comment]
yeah, `npm install aurelia-pal` doesn't work either, for me

**Comment by jsobell** [comment]
It also breaks `typings`:

```
typings ERR! message Unable to resolve "npm:aurelia-pal/dist/commonjs/aurelia-pal.d.ts" from "aurelia-pal"
typings ERR! caused by Unable to find "node_modules\aurelia-pal\dist\commonjs\aurelia-pal.d.ts" from "C:\SPA\Insight.Manager.SPA"
```

**Comment by EisenbergEffect** [comment]
Update typings to latest and `typings install aurelia-pal`. This is the correct way to handle typings going forward if you aren't using npm for modules. If you are using npm, it should work automatically. @niieani can provide an explanation when he wakes up :)

**Comment by MaximBalaganskiy** [comment]
Sorry, it's not over yet :)

```
Error   TS2498  Module ''aurelia-pal'' uses 'export =' and cannot be used with 'export *'.  TypeScript Virtual Projects C:\Dev\Horsie\src\Horsie\wwwroot\jspm_packages\npm\aurelia-framework@1.0.0-beta.1.2.5\aurelia-framework.d.ts    232 IntelliSense    Active
```

Also, typings fetches 1.2.2 version of d.ts

**Comment by EisenbergEffect** [comment]
Check to make sure you don't have a hard-coded typings info somewhere. We just tested this on two separate machines and OSes.

**Comment by MaximBalaganskiy** [comment]
the error comes from `aurelia-framework@1.0.0-beta.1.2.5/aurelia-framework.d.ts` installed in `jspm_packages`

Typings are wrapped like this

```
declare module 'aurelia-pal' {
import alias = require('~aurelia-pal/aurelia-pal');
export = alias;
}
```

**Comment by MaximBalaganskiy** [comment]
If i replace `export * from 'aurelia-pal';` with `export {DOM} from 'aurelia-pal';` in `aurelia-framework.d.ts` - no errors

**Comment by jsobell** [comment]
So to clarify things, we're either all doing something fundamentally wrong, or it doesn't work.
If we move the typings.json entry from `globalDependencies` to `dependencies` the typings will install, but unless the library is either excluded completely (which is what I do) or the \* is replaced with {DOM} (for those who need the DOM object) it just doesn't work.
The fact the latest webpack-loader is broken didn't help, and the new webpack-typescript skeleton app is a complete shemozzle and doesn't run on Windows or OSX so we can't test against a vanilla solution

**Comment by EisenbergEffect** [comment]
As stated on this week's blog announcement, we are pushing out pre-rc updates this week which may cause breaking changes. So, we advise you not to update unless you want to deal with that.

The release process involves configuration changes which have to be made incrementally. This is why we only pushed out `pal` rather than a bunch of libraries. We need to test how this works in a number of scenarios and it's not something we can do all at once. Much of this relates to TypeScript tooling and us actually aligning our configuration with the correct way to handle d.ts files based on what Microsoft says. We've been using a hack up to this point. Now we are getting it right.

The Skeletons have not even been released, so if you are using master with those, that's always an "at your risk" venture. Often times the skeletons also require multiple dependencies which is why we don't release them until their sub-dependencies are released. Our docs always point to official releases of the skeletons so I would advise using those unless you want to slog into the in-progress updates.

Thanks everyone for providing the feedback. We are looking into all the issues now and will be pushing out updates. @niieani will provide some guidance here as we proceed.

**Comment by jbeacham** [comment]
I am getting the same errors as @jsobell and @MaximBalaganskiy. I am having to change \* to {DOM} or exclude the library for it to work with aurelia-framework.

**Comment by niieani** [comment]
Please see the following comment and follow the instructions to fix this problem:

https://github.com/aurelia/skeleton-navigation/issues/477#issuecomment-225183072

**Comment by EisenbergEffect** [comment]
We have a fix coming soon. It's related to a change in d.ts file format. The change we are making is actually per Microsoft's recommendations. However, since not all file formats have been changed yet, there are some conflicts (the process is tedious and takes some time.) @niieani is working to update kits so that other developers aren't affected during this in-between time. He's left instructions above for you for now.

**Comment by EisenbergEffect** [comment]
We'll keep this issue open for now as a reference for anyone else that has these problems.

**Comment by dkent600** [comment]
Is there an up-to-date list of aurelia modules requiring "npm install" rather than "jspm install" (the former was recommended above, and worked for me to get aurelia-pal working)?

**Comment by niieani** [comment]
@dkent600 you don't need any aurelia modules installed with `npm install` when using JSPM. Just use [this typings.json](https://github.com/niieani/skeleton-navigation-typescript/blob/2d2800264083609af698e1fc343dc8928948a4fe/skeleton-typescript/tsconfig.json) and run `typings install`.
